import "./figma.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxProvider from "./_features/ReduxProvider";
import Body from "./body";
import NavbarSC from "./_components/Navbar/NavbarSC";
import Footer from "./_components/Footer/Footer";
import { Analytics } from "@vercel/analytics/next";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <Analytics />
        <Body className={`${inter.variable} antialiased`}>
          <NavbarSC />
          {children}
          <Footer />
        </Body>
      </ReduxProvider>
    </html>
  );
}
