import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./figma.css";
import "./globals.css";
import ReduxProvider from "./_features/ReduxProvider";
import Body from "./body";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <Body className={`${inter.variable} antialiased`}>{children}</Body>
      </ReduxProvider>
    </html>
  );
}
